# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IMP02.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from math import cosh
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage
from Functions import *


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1159, 879)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.undoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.undoBtn.setGeometry(QtCore.QRect(770, 410, 111, 41))
        self.undoBtn.setObjectName("undoBtn")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(920, 410, 111, 41))
        self.saveBtn.setObjectName("saveBtn")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(740, 70, 351, 41))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1080, 150, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(700, 150, 381, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.redSlider = QtWidgets.QSlider(self.layoutWidget)
        self.redSlider.setMinimum(0)
        self.redSlider.setMaximum(50)
        self.redSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redSlider.setObjectName("redSlider")
        self.verticalLayout.addWidget(self.redSlider)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.greenSlider = QtWidgets.QSlider(self.layoutWidget)
        self.greenSlider.setMinimum(0)
        self.greenSlider.setMaximum(50)
        self.greenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenSlider.setObjectName("greenSlider")
        self.verticalLayout.addWidget(self.greenSlider)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.blueSlider = QtWidgets.QSlider(self.layoutWidget)
        self.blueSlider.setMinimum(0)
        self.blueSlider.setMaximum(50)
        self.blueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueSlider.setObjectName("blueSlider")
        self.verticalLayout.addWidget(self.blueSlider)
        self.lbImage = QtWidgets.QLabel(self.centralwidget)
        self.lbImage.setGeometry(QtCore.QRect(11, 51, 681, 691))
        self.lbImage.setText("")
        self.lbImage.setTextFormat(QtCore.Qt.PlainText)
        self.lbImage.setObjectName("lbImage")
        self.openBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openBtn.setGeometry(QtCore.QRect(180, 790, 111, 41))
        self.openBtn.setObjectName("openBtn")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(410, 790, 91, 41))
        self.resetBtn.setObjectName("resetBtn")
        self.valueRed = QtWidgets.QLabel(self.centralwidget)
        self.valueRed.setGeometry(QtCore.QRect(1090, 200, 47, 13))
        self.valueRed.setObjectName("valueRed")
        self.valueGreen = QtWidgets.QLabel(self.centralwidget)
        self.valueGreen.setGeometry(QtCore.QRect(1090, 270, 47, 13))
        self.valueGreen.setObjectName("valueGreen")
        self.valueBlue = QtWidgets.QLabel(self.centralwidget)
        self.valueBlue.setGeometry(QtCore.QRect(1090, 340, 47, 13))
        self.valueBlue.setObjectName("valueBlue")
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1159, 21))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        self.openBtn.clicked.connect(self.openImage)
        self.resetBtn.clicked.connect(self.resetImage)
        self.undoBtn.clicked.connect(self.undoImage)
        self.saveBtn.clicked.connect(self.saveImage)
        self.redSlider.valueChanged['int'].connect(self.changeRed)
        self.greenSlider.valueChanged['int'].connect(self.changeGreen)
        self.blueSlider.valueChanged['int'].connect(self.changeBlue)
        self.redSlider.valueChanged['int'].connect(self.valueRed.setNum)
        self.greenSlider.valueChanged['int'].connect(self.valueGreen.setNum)
        self.blueSlider.valueChanged['int'].connect(self.valueBlue.setNum)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def openImage(self):
        self.filename = QFileDialog.getOpenFileName(filter="image (*.*)")[0]
        self.image = cv2.imread(self.filename)
        self.originimage = self.image
        self.setPhoto(self.image)

    def resetImage(self):
        self.image = self.originimage
        self.setPhoto(self.image)

    def saveImage(self):
        self.image = self.temping

    def undoImage(self):
        self.temping = self.image
        self.setPhoto(self.image)

    def setPhoto(self,image):
        self.tmp = image
        image = imutils.resize(image,width=480)
        frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = QImage(frame,frame.shape[1],frame.shape[0],frame.strides[0],QImage.Format_RGB888)
        self.lbImage.setPixmap(QtGui.QPixmap.fromImage(image))
    
    def changeRed(self,value):
        rgb = cv2.cvtColor(self.image,cv2.COLOR_BGR2RGB)
        r, g, b = cv2.split(rgb)
        #[red, green, blue]
        lim = value
        r = r + lim
        # g = g - lim
        # b = b - lim
        final_rgb = cv2.merge((r, g, b))
        self.temping = cv2.cvtColor(final_rgb,cv2.COLOR_RGB2BGR)
        self.setPhoto(self.temping)
    
    def changeGreen(self,value):
        rgb = cv2.cvtColor(self.image,cv2.COLOR_BGR2RGB)
        r, g, b= cv2.split(rgb)
        lim = value
        g = g + lim
        # r = r - lim
        # b = b - lim
        final_rgb = cv2.merge((r, g, b))
        self.temping = cv2.cvtColor(final_rgb,cv2.COLOR_RGB2BGR)
        self.setPhoto(self.temping)
    
    def changeBlue(self,value):
        rgb = cv2.cvtColor(self.image,cv2.COLOR_BGR2RGB)
        r, g, b = cv2.split(rgb)
        lim = value
        b = b + lim
        # r = r - lim
        # g = g - lim
        final_rgb = cv2.merge((r, g, b))
        self.temping = cv2.cvtColor(final_rgb,cv2.COLOR_RGB2BGR)
        self.setPhoto(self.temping)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.undoBtn.setText(_translate("Main", "Undo"))
        self.saveBtn.setText(_translate("Main", "Save"))
        self.textEdit.setHtml(_translate("Main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Color Balancing</span></p></body></html>"))
        self.label.setText(_translate("Main", "Color Level"))
        self.label_2.setText(_translate("Main", "Red"))
        self.label_3.setText(_translate("Main", "Green"))
        self.label_4.setText(_translate("Main", "Blue"))
        self.openBtn.setText(_translate("Main", "Open"))
        self.resetBtn.setText(_translate("Main", "Reset"))
        self.valueRed.setText(_translate("Main", "0"))
        self.valueGreen.setText(_translate("Main", "0"))
        self.valueBlue.setText(_translate("Main", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
