# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IMP02.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage
from Functions import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1159, 879)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.undoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.undoBtn.setGeometry(QtCore.QRect(770, 410, 111, 41))
        self.undoBtn.setObjectName("undoBtn")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(920, 410, 111, 41))
        self.saveBtn.setObjectName("saveBtn")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(740, 70, 351, 41))
        self.textEdit.setObjectName("textEdit")
        self.redBox = QtWidgets.QTextEdit(self.centralwidget)
        self.redBox.setGeometry(QtCore.QRect(1090, 191, 51, 31))
        self.redBox.setObjectName("redBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1080, 150, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.greenBox = QtWidgets.QTextEdit(self.centralwidget)
        self.greenBox.setGeometry(QtCore.QRect(1090, 260, 51, 31))
        self.greenBox.setObjectName("greenBox")
        self.blueBox = QtWidgets.QTextEdit(self.centralwidget)
        self.blueBox.setGeometry(QtCore.QRect(1090, 330, 51, 31))
        self.blueBox.setObjectName("blueBox")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(700, 150, 381, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.redSlider = QtWidgets.QSlider(self.layoutWidget)
        self.redSlider.setMinimum(0)
        self.redSlider.setMaximum(100)
        self.redSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redSlider.setObjectName("redSlider")
        self.verticalLayout.addWidget(self.redSlider)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.greenSlider = QtWidgets.QSlider(self.layoutWidget)
        self.greenSlider.setMinimum(0)
        self.greenSlider.setMaximum(100)
        self.greenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenSlider.setObjectName("greenSlider")
        self.verticalLayout.addWidget(self.greenSlider)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.blueSlider = QtWidgets.QSlider(self.layoutWidget)
        self.blueSlider.setMinimum(0)
        self.blueSlider.setMaximum(100)
        self.blueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueSlider.setObjectName("blueSlider")
        self.verticalLayout.addWidget(self.blueSlider)
        self.lbImage = QtWidgets.QLabel(self.centralwidget)
        self.lbImage.setGeometry(QtCore.QRect(11, 51, 681, 691))
        self.lbImage.setText("")
        self.lbImage.setTextFormat(QtCore.Qt.PlainText)
        self.lbImage.setObjectName("lbImage")
        self.openBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openBtn.setGeometry(QtCore.QRect(180, 790, 111, 41))
        self.openBtn.setObjectName("openBtn")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(410, 790, 91, 41))
        self.resetBtn.setObjectName("resetBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1159, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.openBtn.clicked.connect(self.openImage)
        self.resetBtn.clicked.connect(self.resetImage)
        self.undoBtn.clicked.connect(self.undoImage)
        self.saveBtn.clicked.connect(self.saveImage)
        self.redSlider.valueChanged['int'].connect(self.changeRed)
        self.greenSlider.valueChanged['int'].connect(self.lbImage.setNum)
        self.blueSlider.valueChanged['int'].connect(self.lbImage.setNum)
        self.redSlider.valueChanged['int'].connect(self.redBox.clear)
        self.greenSlider.valueChanged['int'].connect(self.greenBox.clear)
        self.blueSlider.valueChanged['int'].connect(self.blueBox.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.GNoiseVar = 0
        self.GNoiseMean = 0
        self.GNoiseSeed = 0

    def openImage(self):
        self.filename = QFileDialog.getOpenFileName(filter="image (*.*)")[0]
        self.image = cv2.imread(self.filename)
        self.originimage = self.image
        self.setPhoto(self.image)

    def resetImage(self):
        self.image = self.originimage
        self.setPhoto(self.image)

    def saveImage(self):
        self.image = self.tempimg

    def undoImage(self):
        self.tempimg = self.image
        self.setPhoto(self.image)
    def setPhoto(self,image):
        self.tmp = image
        image = imutils.resize(image,width=480)
        frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = QImage(frame,frame.shape[1],frame.shape[0],frame.strides[0],QImage.Format_RGB888)
        self.lbImage.setPixmap(QtGui.QPixmap.fromImage(image))
#ddd
    def changeRed(self,value):
        self.GNoiseVar = (value/100.0)**2
        self.tempimg = AddGaussianNoise(self.image,self.GNoiseSeed,self.GNoiseMean,self.GNoiseVar)
        self.setPhoto(self.tempimg)

    def changeGNoiseSeed(self,value):
        self.GNoiseSeed = value
        self.tempimg = AddGaussianNoise(self.image,self.GNoiseSeed,self.GNoiseMean,self.GNoiseVar)
        self.setPhoto(self.tempimg)

    def changeGNoiseMean(self,value):
        self.GNoiseMean = value/255.0
        self.tempimg = AddGaussianNoise(self.image,self.GNoiseSeed,self.GNoiseMean,self.GNoiseVar)
        self.setPhoto(self.tempimg)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.undoBtn.setText(_translate("MainWindow", "Undo"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                         "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Color Balancing</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Color Level"))
        self.label_2.setText(_translate("MainWindow", "Red"))
        self.label_3.setText(_translate("MainWindow", "Green"))
        self.label_4.setText(_translate("MainWindow", "Blue"))
        self.openBtn.setText(_translate("MainWindow", "Open"))
        self.resetBtn.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
